# Generated by Django 3.2.5 on 2021-08-27 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conf_center', '0001_initial'),
        ('host', '0004_alter_host_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='名称/标题')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='描述信息')),
                ('tag', models.CharField(max_length=32, unique=True, verbose_name='应用唯一标识号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '应用管理',
                'verbose_name_plural': '应用管理',
                'db_table': 'release_app',
            },
        ),
        migrations.CreateModel(
            name='ReleaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='名称/标题')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='描述信息')),
                ('code_git_addr', models.CharField(max_length=128, verbose_name='Git仓库地址,注意我们使用的是ssh地址')),
                ('git_project_name', models.CharField(max_length=128, verbose_name='项目名称/目录名称')),
                ('msg_notice_status', models.BooleanField(default=False, verbose_name='发布审核开启')),
                ('msg_type', models.IntegerField(choices=[(0, '关闭'), (1, '钉钉'), (2, '短信'), (3, '邮件')], default=0, verbose_name='审核通知方式')),
                ('msg_content', models.CharField(max_length=128, verbose_name='审核通知内容')),
                ('target_host_pub_path', models.CharField(max_length=128, verbose_name='远程主机的发布路径')),
                ('target_host_repository_path', models.CharField(max_length=128, verbose_name='远程主机的git仓库地址')),
                ('keep_history_count', models.IntegerField(default=5, verbose_name='远程主机中代码的历史版本数量')),
                ('filefilterway', models.IntegerField(choices=[(0, '包含'), (1, '排除')], help_text='默认是包含', verbose_name='文件过滤方式')),
                ('file_filter_cmd_content', models.TextField(blank=True, null=True, verbose_name='需要过滤的文件或者目录, 通过换行符分隔')),
                ('before_code_check_out_value', models.TextField(verbose_name='代码检出前的执行动作')),
                ('before_release_content', models.TextField(blank=True, help_text='在管理的目标主机执行', null=True, verbose_name='代码发布前的执行动作')),
                ('custom_global_variable', models.TextField(blank=True, help_text='全局变量设置', null=True, verbose_name='全局变量')),
                ('after_code_check_out_value', models.TextField(blank=True, help_text='在Hippo项目所在服务器执行的', null=True, verbose_name='代码检出后的动作')),
                ('after_release_value', models.TextField(blank=True, help_text='在目标主机执行的', null=True, verbose_name='代码发布后执行')),
                ('envs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_envs', to='conf_center.environment', verbose_name='发布环境')),
                ('release_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_appliction', to='release.releaseapp', verbose_name='发布从属应用')),
            ],
            options={
                'verbose_name': '发布记录',
                'verbose_name_plural': '发布记录',
                'db_table': 'release_record',
            },
        ),
        migrations.CreateModel(
            name='ReleaseRecordDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='名称/标题')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='描述信息')),
                ('hosts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_host', to='host.host', verbose_name='发布的主机')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_record', to='release.releaserecord', verbose_name='发布记录')),
            ],
            options={
                'verbose_name': '发布记录详情',
                'verbose_name_plural': '发布记录详情',
                'db_table': 'release_record_detail',
            },
        ),
        migrations.CreateModel(
            name='ReleaseApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='名称/标题')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='描述信息')),
                ('git_release_branch_or_tag', models.IntegerField(choices=[(1, '分支'), (2, '标签')], default=1, verbose_name='分支/标签')),
                ('git_release_version', models.CharField(max_length=128, verbose_name='发布版本(其实是哪个分支或者哪个标签)')),
                ('git_release_commit_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='git_commit_id')),
                ('release_status', models.IntegerField(choices=[(1, '待审核'), (2, '待发布'), (3, '发布成功'), (4, '发布异常'), (5, '其他')], default=1, verbose_name='状态')),
                ('release_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_record_apply', to='release.releaserecord', verbose_name='发布记录')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='release_apply_user', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '发布申请记录表',
                'verbose_name_plural': '发布申请记录表',
                'db_table': 'release_apply',
            },
        ),
    ]
