# Generated by Django 3.2.5 on 2021-08-30 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseapply',
            name='release_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='release_apply_release_user', to=settings.AUTH_USER_MODEL, verbose_name='发布人'),
        ),
        migrations.AddField(
            model_name='releaseapply',
            name='review_desc',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='审核意见'),
        ),
        migrations.AddField(
            model_name='releaseapply',
            name='review_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='release_apply_review_user', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AlterField(
            model_name='releaseapply',
            name='git_release_commit_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='git_commit_id'),
        ),
        migrations.AlterField(
            model_name='releaseapply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_apply_user', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AlterModelTable(
            name='releaseapply',
            table='hp_release_apply',
        ),
    ]
