# Generated by Django 3.2.5 on 2021-08-30 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0002_auto_20210830_1457'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='releaseapply',
            table='release_apply',
        ),
    ]
