# Generated by Django 3.2.5 on 2021-08-23 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='host',
            table='host',
        ),
        migrations.AlterModelTable(
            name='hostcategory',
            table='host_category',
        ),
    ]
