# Generated by Django 3.2.5 on 2021-08-26 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conf_center', '0001_initial'),
        ('host', '0002_auto_20210823_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='environment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='conf_center.environment', verbose_name='从属环境'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip_addr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='连接地址'),
        ),
        migrations.AlterModelTable(
            name='host',
            table='hp_host',
        ),
    ]
