# Generated by Django 3.2.5 on 2021-08-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_auto_20210826_1302'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='host',
            table='host',
        ),
    ]
